# Generated by Django 4.0.2 on 2022-03-10 04:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('item_card', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item_card',
            name='img_category',
            field=models.ForeignKey(default=5, on_delete=django.db.models.deletion.CASCADE, to='item_card.category'),
        ),
    ]
