# Generated by Django 4.0.2 on 2022-03-15 04:59

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('item_card', '0004_item_card_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_price', models.FloatField()),
                ('product_quantity', models.IntegerField()),
                ('date', models.DateField(default=datetime.datetime.today)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='item_card.customer')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='item_card.item_card')),
            ],
        ),
    ]
